### ISSUE TITLE
Add audio to video

### ISSUE THREAD

**Issue by eroj333** [amitness/major-project#12]
Currently, audio is removed from video. We should find a way to bring that audio back.

**Comment by Kamalpaneru** [comment]
@eroj333 two ways to do it .. Either using ffmpeg or converting .mp4 to .mp3 using Converter.

**Comment by Kamalpaneru** [comment]
@amitness @eroj333 the converter library is not working and i can't find a solid wrapper for ffmpeg that can achieve this task .. so maybe we can install ffmpeg and run it via python subprocess?? 
like this
![selection_028](https://user-images.githubusercontent.com/13826932/36933019-5309db4c-1efa-11e8-984f-fd1be25b1575.png)

for this we need to install ffmpeg which is not a python library btw ... i don't know if its a good idea ...

**Comment by amitness** [comment]
@Kamalpaneru Close it?
